name: catch_the_ball
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Updated dev dependencies
  async: ^2.13.0  # Updated version
  fake_async: ^1.3.3  # Updated version
  leak_tracker: ^10.0.9  # Updated version
  vm_service: ^15.0.0  # Updated version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
